apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test-copilot-1"

  links:
    - url: https://github.com/ItRachii/aws-elasticbeanstalk-20231110105054
      title: "test-copilot-1"
      icon: code

  labels:
    system: web-apps
    trackid: "aws-elasticbeanstalk-20231110105054"
    environmentname: test-copilot-env

  tags:
    - java
    - aws
    - "applicationtype-webapplication"

  annotations:
    # add elastic beanstalk annotation
    jenkins.io/github-folder: 'custom-actions/tf-test-copilot-1'
    github.com/project-slug: ItRachii/aws-elasticbeanstalk-20231110105054
    backstage.io/techdocs-ref: dir:.
    backstage.io/linguist: https://github.com/ItRachii/spring-boot-ebs
    sonarqube.org/project-key: 'demo-app/aws-elb-java'

spec:
  type: service
  lifecycle: experimental
  system: elasticbeanstalk
  owner: "group:default/ey"
